### ISSUE TITLE
Resources not loading

### ISSUE THREAD

**Issue by juraj-hrivnak** [anatawa12/migrating-ForgeGradle-3.2-to-4.x#1]
#### Resources stopped working after updating to Forge Gradle 4.1 from 2.3

I tried to add:
```gradle
sourceSets {
    main {
        output.resourcesDir = file('build/combined')
        java.outputDir = file('build/combined')
    }
}
```
But it's still not loading

- My build.gradle:
https://github.com/juraj-hrivnak/Crocodilite/blob/master/build.gradle.kts

**Comment by anatawa12** [comment]
I'm sorry for not testing enough. I'll fix it and I'll send you PR.

**Comment by anatawa12** [comment]
Sorry for me to not know, It's a bug of userdev. I've added the commit adds a workaround for this bug to this repository (https://github.com/anatawa12/migrating-ForgeGradle-3.2-to-4.x/commit/891dec61546c451386e7f38dcbad61853c0208cc). I'm creating PullRequest for your mod.

**Comment by juraj-hrivnak** [comment]
No worries. I really appreciate your help.
Thank you so much!
